### ISSUE TITLE
antd-init 命令是报错

### ISSUE THREAD

**Issue by jiangjinpeng21** [ant-design/antd-bin#22]
用的是node.js 5.0 集成npm  
windows 7 64

D:\antd-demo>antd-init
Write ..eslintrc
Write .\gitignore
Write .\index.html
Write .\package.json
Write .\README.md
Write .\lib.js
Write .\App.jsx
Write .\index.jsx
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn which ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

**Comment by wsw** [comment]
我也遇到了

**Comment by sorrycc** [comment]
修复了，+ antd-init@0.1.7
