### ISSUE TITLE
npm run dev 启动报错 

### ISSUE THREAD

**Issue by yaofan** [ant-design/antd-bin#27]
按照文档的步骤安装后，启动就报错了。 另外安装Ant Design React 的快速开发的文档，启动后报同样的错误。 

   SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/usr/local/lib/node_modules/antd-bin/lib/server.js:16:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/antd-bin/bin/antd-server:11:25)
    at Module._compile (module.js:460:26)
yaodeMacBook-Air-2:grizzli yao$

**Comment by afc163** [comment]
升级 node 到 4.x 以上。
