### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by JonneyYan** [ant-design/antd-bin#31]
按照步骤执行了antd-init 和npm install，但run dev时出现如此错误：

```
ERROR in Cannot find module '../modules/web.dom.iterable'
```

**Comment by JonneyYan** [comment]
npm-log如下

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\PC-109540\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.5.1
3 info using node@v4.2.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle antd-demo@1.0.0~predev: antd-demo@1.0.0
6 silly lifecycle antd-demo@1.0.0~predev: no script for predev, continuing
7 info lifecycle antd-demo@1.0.0~dev: antd-demo@1.0.0
8 verbose lifecycle antd-demo@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle antd-demo@1.0.0~dev: PATH: C:\Users\PC-109540\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\cygwin64\home\PC-109540\sdk\node_modules\.bin;C:\Users\PC-109540\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\cygwin64\home\PC-109540\sdk\node_modules\.bin;C:\cygwin64\bin;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Users\PC-109540\AppData\Local\atom\bin;C:\Users\PC-109540\AppData\Roaming\npm
10 verbose lifecycle antd-demo@1.0.0~dev: CWD: C:\cygwin64\home\PC-109540\sdk
11 silly lifecycle antd-demo@1.0.0~dev: Args: [ '/d /s /c', 'dora -p 8001 --plugins atool-build,proxy' ]
12 silly lifecycle antd-demo@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle antd-demo@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: antd-demo@1.0.0 dev: `dora -p 8001 --plugins atool-build,proxy`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\PC-109540\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\PC-109540\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid antd-demo@1.0.0
16 verbose cwd C:\cygwin64\home\PC-109540\sdk
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PC-109540\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v4.2.3
20 error npm  v3.5.1
21 error code ELIFECYCLE
22 error antd-demo@1.0.0 dev: `dora -p 8001 --plugins atool-build,proxy`
22 error Exit status 1
23 error Failed at the antd-demo@1.0.0 dev script 'dora -p 8001 --plugins atool-build,proxy'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the antd-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     dora -p 8001 --plugins atool-build,proxy
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs antd-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls antd-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sorrycc** [comment]
感觉依赖没装好。
